### ISSUE TITLE
网页自定义回复插件为什么去掉了？

### ISSUE THREAD

**Issue by isaac1216** [pcrbot/plugins-for-Hoshino#16]
之前一直用的shebot的网页自定义回复插件，个人觉得相当好用，近期突然发现大佬的插件更新了，不知为什么把网页自定义回复给去掉了？

**Comment by shewinder** [comment]
有些bug，修复了再放上来（咕）

**Comment by isaac1216** [comment]
> 有些bug，修复了再放上来（咕）

非常感谢大佬的这个插件（当然还有涩图插件），我已经差不多用这个插件两个月了，我是用来录轴、取轴，之前会里录轴抄作业乱得一塌糊涂，这个插件方便了许多！
